# Generated by Django 5.1.2 on 2025-06-28 06:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_aboutpage_options_alter_homepage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1), ("image", 2), ("about_block", 9)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Project or role title", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Project description", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link to the project or company",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {"help_text": "Start date", "required": True},
                    ),
                    7: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {
                            "help_text": "End date (leave blank if current)",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Current position?",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("description", 4),
                                ("url", 5),
                                ("start_date", 6),
                                ("end_date", 7),
                                ("is_current", 8),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
