# Generated by Django 5.1.2 on 2025-06-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("url", models.URLField()),
                (
                    "icon",
                    models.FileField(
                        help_text="Upload an SVG file", upload_to="social_icons/"
                    ),
                ),
            ],
        ),
    ]
