# Generated by Django 5.1.2 on 2025-06-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sociallink",
            name="icon",
        ),
        migrations.AddField(
            model_name="sociallink",
            name="dark_icon",
            field=models.FileField(
                default="",
                help_text="Upload an SVG file (bg-neutral-400)",
                upload_to="social_icons/",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sociallink",
            name="light_icon",
            field=models.FileField(
                default="does not exist",
                help_text="Upload an SVG file (bg-neutral-600)",
                upload_to="social_icons/",
            ),
            preserve_default=False,
        ),
    ]
