upstream notes {
    # Droplet private IP + Port
    server 10.106.0.4:8000;
 }

upstream links {
    # Droplet private IP + port
    server 10.106.0.4:8001;
}

upstream portfolio {
    # Docker compose service name
    server web:8000;
}

# Portfolio server block
server {

    listen 80;
    server_name bayford.dev www.bayford.dev;

    # Digital ocean load balancer health check
    location = /health {
        return 200 "OK";
        add_header Content-Type text/plain;
    }

    location / {
        proxy_pass http://portfolio;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;

        proxy_redirect off;
        client_max_body_size 20M;
    }

    location /static/ {
        alias /home/app/web/staticfiles/;
    }

    location /media/ {
        alias /home/app/web/mediafiles/;
    }

}

# Notes app block
server {

    listen 80;
    server_name notes.bayford.dev www.notes.bayford.dev;

    location / {
        proxy_pass http://notes;

        # preserve original host/scheme/client IP
        proxy_set_header Host              $host;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;

        proxy_redirect off;
        client_max_body_size 20M;
    }
    # App uses WhiteNoise for static files
}

# Links app block
server {

    listen 80;
    server_name links.bayford.dev www.links.bayford.dev;

    location / {
        proxy_pass http://links;

        # preserve original host/scheme/client IP
        proxy_set_header Host              $host;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;

        proxy_redirect off;
        client_max_body_size 20M;
    }
    # App uses WhiteNoise for static files
}