# Generated by Django 5.1.2 on 2025-06-28 11:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogindexpage",
            options={"verbose_name": "Blog Index"},
        ),
        migrations.AlterModelOptions(
            name="blogpostpage",
            options={"verbose_name": "Blog Post", "verbose_name_plural": "Blog Posts"},
        ),
        migrations.AlterField(
            model_name="blogpostpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1), ("image", 2), ("about_block", 6)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("python", "Python"),
                                ("javascript", "JavaScript"),
                            ],
                            "help_text": "",
                        },
                    ),
                    4: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "The code snippet", "required": True},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Caption for code snippet", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 3), ("content", 4), ("caption", 5)]],
                        {},
                    ),
                },
            ),
        ),
    ]
