# Generated by Django 5.1.2 on 2025-06-29 17:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogtag_alter_blogpostpage_body_taggedblog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpostpage",
            name="preview",
            field=wagtail.fields.RichTextField(
                default="Please fill me in",
                help_text="Used on home page to preview post",
            ),
        ),
    ]
